# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# Node 

name: Bonga_Ke Continous Integration (server config)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Check Node.js version ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: node --version
      name: Check node version
    - run: npm --version
      name: Check npm version
    - run: npm ci
      name: Install all dependencies
    - run: npm start
      name: Start server application
